### ISSUE TITLE
Libfontconfig Error on Vercel Deployment

### ISSUE THREAD

**Issue by lecramr** [Loskir/styled-qr-code#10]
Hey,

thanks for your great library, it's working great on my local machine, if deployed to Vercel it's crashing about 50% of the time calling the generation Endpoint, with following error:

`Unhandled Rejection: Error: libfontconfig.so.1: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1454:18)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at /opt/rust/nodejs.js:1:11612
    at Function.cr (/opt/rust/nodejs.js:1:11986)
    at e.<computed>.re._load (/opt/rust/nodejs.js:1:11582)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/var/task/node_modules/.pnpm/skia-canvas@1.0.2/node_modules/skia-canvas/lib/index.js:23:29)
    at Module._compile (node:internal/modules/cjs/loader:1358:14) {
  code: 'ERR_DLOPEN_FAILED'
}`

Is there any fix for this issue?

Thanks in advance! :)

**Comment by MATTiVOLTARii** [comment]
Is there a solution for this now?
