### ISSUE TITLE
Issues when embedding SVG images in center

### ISSUE THREAD

**Issue by HyperGeil** [Loskir/styled-qr-code#7]
I have an issues when referencing SVG images for embedding in the center like:

image: "https://upload.wikimedia.org/wikipedia/commons/f/f5/History_Logo.svg",

Then I get the following error:

          else onerror(new Error("Could not decode image data"))
                       ^

Error: Could not decode image data
    at C:\Development\Node.js - QR API\node_modules\skia-canvas\lib\index.js:880:24
    at C:\Development\Node.js - QR API\node_modules\skia-canvas\node_modules\simple-get\index.js:98:7
    at PassThrough.<anonymous> (C:\Development\Node.js - QR API\node_modules\simple-concat\index.js:8:13)
    at Object.onceWrapper (node:events:632:28)
    at PassThrough.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.12.2

I am using VS Code - and test in the terminal - it works with PNG logo files.

**Comment by emblaszkiewicz** [comment]
Hi! Did you manage to add SVG images? If so, how did you accomplish that?
